
Gladius2DB = {
	["profileKeys"] = {
		["YourCharacterName - Maelstrom"] = "YourCharacterName - Maelstrom",
	},
	["profiles"] = {
		["YourCharacterName - Maelstrom"] = {
			["backgroundColor"] = {
				["a"] = 0,
			},
			["drTrackerFrameLevel"] = 5,
			["drTrackerCooldown"] = true,
			["castTextOffsetX"] = 3,
			["powerBarHeight"] = 10,
			["timerOmniCC"] = true,
			["frameScale"] = 1.3,
			["auraVersion"] = 1,
			["tagsVersion"] = 1,
			["locked"] = true,
			["advancedOptions"] = true,
			["y"] = {
				["arena1"] = 507.9111507320438,
			},
			["healthBarHeight"] = 20,
			["tagsTexts"] = {
				["PowerBar Left Text"] = {
					["text"] = "[spec:short]",
				},
				["HealthBar Right Text"] = {
					["text"] = "",
				},
				["PowerBar Right Text"] = {
					["text"] = "[power:short]",
				},
			},
			["castBarHeight"] = 30,
			["alerts"] = {
				["drinking"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["groundingDropped"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["groundingDied"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["lostDebuff"] = {
					["speech"] = true,
					["excludes"] = {
						["Warrior"] = "WARRIOR",
						["Paladin"] = "PALADIN",
						["Shaman"] = "SHAMAN",
						["Rogue"] = "ROGUE",
						["Mage"] = "MAGE",
						["Druid"] = "DRUID",
						["Priest"] = "PRIEST",
						["Hunter"] = "HUNTER",
						["Death Knight"] = "DEATHKNIGHT",
						["Warlock"] = "WARLOCK",
					},
					["soundEffect"] = true,
					["options"] = {
						["debuff1"] = "",
						["debuff2"] = "",
						["debuff3"] = "",
					},
				},
				["tremorDied"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["wotfAvailable"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["ccsOnPartner"] = {
					["excludes"] = {
						["Intimidating Shout"] = "Intimidating Shout",
						["Polymorph"] = "Polymorph",
						["Ring of Frost"] = "Ring of Frost",
						["Scare Beast"] = "Scare Beast",
						["Fear"] = "Fear",
						["Hex"] = "Hex",
						["Howl of Terror"] = "Howl of Terror",
						["Repentance"] = "Repentance",
						["Wyvern Sting"] = "Wyvern Sting",
						["Freeze"] = "Freeze",
						["Hibernate"] = "Hibernate",
						["Seduction"] = "Seduction",
						["Psychic Scream"] = "Psychic Scream",
						["Blind"] = "Blind",
						["Sap"] = "Sap",
						["Entangling Roots"] = "Entangling Roots",
						["Frost Nova"] = "Frost Nova",
						["Hungering Cold"] = "Hungering Cold",
						["Freezing Trap"] = "Freezing Trap",
						["Cyclone"] = "Cyclone",
					},
					["speech"] = true,
					["soundEffect"] = true,
				},
				["tremorDropped"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["gainedBuff"] = {
					["speech"] = true,
					["excludes"] = {
						["Warrior"] = "WARRIOR",
						["Paladin"] = "PALADIN",
						["Shaman"] = "SHAMAN",
						["Rogue"] = "ROGUE",
						["Mage"] = "MAGE",
						["Druid"] = "DRUID",
						["Priest"] = "PRIEST",
						["Hunter"] = "HUNTER",
						["Death Knight"] = "DEATHKNIGHT",
						["Warlock"] = "WARLOCK",
					},
					["soundEffect"] = true,
					["options"] = {
						["buff1"] = "",
						["buff2"] = "",
						["buff3"] = "",
					},
				},
				["drExpiration"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["gainedDebuff"] = {
					["speech"] = true,
					["excludes"] = {
						["Warrior"] = "WARRIOR",
						["Paladin"] = "PALADIN",
						["Shaman"] = "SHAMAN",
						["Rogue"] = "ROGUE",
						["Mage"] = "MAGE",
						["Druid"] = "DRUID",
						["Priest"] = "PRIEST",
						["Hunter"] = "HUNTER",
						["Death Knight"] = "DEATHKNIGHT",
						["Warlock"] = "WARLOCK",
					},
					["soundEffect"] = true,
					["options"] = {
						["debuff1"] = "",
						["debuff2"] = "",
						["debuff3"] = "",
					},
				},
				["innervateUsed"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["opponentDeaths"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["friendlySchoolLocks"] = {
					["excludes"] = {
						["Skull Bash"] = "Skull Bash",
						["Mind Freeze"] = "Mind Freeze",
						["Wind Shear"] = "Wind Shear",
						["Pummel"] = "Pummel",
						["Kick"] = "Kick",
						["Throwing Specialization"] = "Throwing Specialization",
						["Spell Lock"] = "Spell Lock",
						["Counterspell"] = "Counterspell",
					},
					["speech"] = true,
					["soundEffect"] = true,
				},
				["lostBuff"] = {
					["speech"] = true,
					["excludes"] = {
						["Warrior"] = "WARRIOR",
						["Paladin"] = "PALADIN",
						["Shaman"] = "SHAMAN",
						["Rogue"] = "ROGUE",
						["Mage"] = "MAGE",
						["Druid"] = "DRUID",
						["Priest"] = "PRIEST",
						["Hunter"] = "HUNTER",
						["Death Knight"] = "DEATHKNIGHT",
						["Warlock"] = "WARLOCK",
					},
					["soundEffect"] = true,
					["options"] = {
						["buff1"] = "",
						["buff2"] = "",
						["buff3"] = "",
					},
				},
				["wotfUsed"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["trinketUsed"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["drExpiration2"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["trinketAvailable"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["friendlySilences"] = {
					["excludes"] = {
						["Strangulate"] = "Strangulate",
						["Nether Shock"] = "Nether Shock",
						["Silenced - Gag Order"] = "Silenced - Gag Order",
						["Solar Beam"] = "Solar Beam",
						["Silencing Shot"] = "Silencing Shot",
						["Arcane Torrent"] = "Arcane Torrent",
						["Silenced - Improved Counterspell"] = "Silenced - Improved Counterspell",
						["Silence"] = "Silence",
						["Silenced - Improved Kick"] = "Silenced - Improved Kick",
						["Garrote - Silence"] = "Garrote - Silence",
						["Dazed - Avenger's Shield"] = "Dazed - Avenger's Shield",
						["Spell Lock"] = "Spell Lock",
					},
					["speech"] = true,
					["soundEffect"] = true,
				},
				["lowHealth"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["invulns"] = {
					["excludes"] = {
						["Divine Shield"] = "Divine Shield",
						["Divine Protection"] = "Divine Protection",
						["Ice Block"] = "Ice Block",
						["Hand of Protection"] = "Hand of Protection",
						["Pain Suppression"] = "Pain Suppression",
						["Survival Instincts"] = "Survival Instincts",
						["Shield Wall"] = "Shield Wall",
						["Dispersion"] = "Dispersion",
					},
					["speech"] = true,
					["soundEffect"] = true,
				},
				["partnerCCs"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["manaTideDropped"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["partnerCastingCC"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
				["hostileSchoolLocks"] = {
					["excludes"] = {
						["Skull Bash"] = "Skull Bash",
						["Mind Freeze"] = "Mind Freeze",
						["Wind Shear"] = "Wind Shear",
						["Pummel"] = "Pummel",
						["Kick"] = "Kick",
						["Throwing Specialization"] = "Throwing Specialization",
						["Spell Lock"] = "Spell Lock",
						["Counterspell"] = "Counterspell",
					},
					["speech"] = true,
					["soundEffect"] = true,
				},
				["hostileSilences"] = {
					["excludes"] = {
						["Strangulate"] = "Strangulate",
						["Nether Shock"] = "Nether Shock",
						["Silenced - Gag Order"] = "Silenced - Gag Order",
						["Solar Beam"] = "Solar Beam",
						["Silencing Shot"] = "Silencing Shot",
						["Arcane Torrent"] = "Arcane Torrent",
						["Silenced - Improved Counterspell"] = "Silenced - Improved Counterspell",
						["Silence"] = "Silence",
						["Silenced - Improved Kick"] = "Silenced - Improved Kick",
						["Garrote - Silence"] = "Garrote - Silence",
						["Dazed - Avenger's Shield"] = "Dazed - Avenger's Shield",
						["Spell Lock"] = "Spell Lock",
					},
					["speech"] = true,
					["soundEffect"] = true,
				},
				["resurrecting"] = {
					["soundEffect"] = true,
					["speech"] = true,
				},
			},
			["castBarBackgroundColor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["x"] = {
				["arena1"] = 1002.666685976957,
			},
		},
	},
}
